#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
#  Qwen Gateway — install.sh
#  Self-hosted OpenAI-compatible API gateway (keyless, powered by Qwen AI)
# ─────────────────────────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

step()  { echo -e "\n${BLUE}${BOLD}[→]${RESET} $*"; }
ok()    { echo -e "${GREEN}${BOLD}[✓]${RESET} $*"; }
warn()  { echo -e "${YELLOW}${BOLD}[!]${RESET} $*"; }
fail()  { echo -e "${RED}${BOLD}[✗]${RESET} $*"; exit 1; }
info()  { echo -e "    ${CYAN}$*${RESET}"; }

# ── Header ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║        Qwen Gateway  •  Install Script       ║${RESET}"
echo -e "${BOLD}║   OpenAI-compatible API  •  No token needed  ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
step "Checking prerequisites"

# Node.js >= 20
if ! command -v node &>/dev/null; then
  fail "Node.js not found. Install from https://nodejs.org (v20 or later)"
fi
NODE_VER=$(node --version | tr -d 'v' | cut -d. -f1)
if [ "$NODE_VER" -lt 20 ]; then
  fail "Node.js v20+ required (found $(node --version))"
fi
ok "Node.js $(node --version)"

# pnpm — install if missing
if ! command -v pnpm &>/dev/null; then
  warn "pnpm not found — installing via npm..."
  npm install -g pnpm@10 --silent
fi
ok "pnpm $(pnpm --version)"

# ── 2. Install dependencies ───────────────────────────────────────────────────
step "Installing workspace dependencies"
pnpm install --frozen-lockfile 2>&1 | grep -E "^(Done|ERR|✓|Packages)" || true
ok "Dependencies installed"

# ── 3. Environment variables ──────────────────────────────────────────────────
step "Configuring environment variables"

ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — skipping interactive setup (delete it to reconfigure)"
else
  echo ""
  echo -e "  ${BOLD}Required credentials${RESET}"
  echo -e "  ─────────────────────────────────────────────"
  echo ""

  # Helper: prompt with default
  prompt_var() {
    local VAR="$1"
    local DESC="$2"
    local DEFAULT="${3:-}"
    local VALUE=""
    if [ -n "$DEFAULT" ]; then
      read -rp "  ${BOLD}${VAR}${RESET} (${DESC}) [${DEFAULT}]: " VALUE
      VALUE="${VALUE:-$DEFAULT}"
    else
      while [ -z "$VALUE" ]; do
        read -rp "  ${BOLD}${VAR}${RESET} (${DESC}): " VALUE
        [ -z "$VALUE" ] && warn "  This field is required"
      done
    fi
    echo "$VALUE"
  }

  MONGODB_URI=$(prompt_var "MONGODB_URI" "MongoDB connection string" "")
  MONGODB_DATABASE=$(prompt_var "MONGODB_DATABASE" "MongoDB database name" "manus")
  REDIS_HOST=$(prompt_var "REDIS_HOST" "Redis host" "localhost")
  REDIS_PORT=$(prompt_var "REDIS_PORT" "Redis port" "6379")
  REDIS_PASSWORD=$(prompt_var "REDIS_PASSWORD" "Redis password (leave blank if none)" " ")
  POSTGRES_URL=$(prompt_var "POSTGRES_URL" "PostgreSQL connection string (optional)" " ")
  JWT_SECRET=$(prompt_var "JWT_SECRET" "JWT secret key (any long random string)" "$(LC_ALL=C tr -dc 'A-Za-z0-9_-' < /dev/urandom 2>/dev/null | head -c 48 || echo "qwen-gateway-$(date +%s)-secret")")
  SESSION_SECRET=$(prompt_var "SESSION_SECRET" "Session secret key" "$(LC_ALL=C tr -dc 'A-Za-z0-9_-' < /dev/urandom 2>/dev/null | head -c 48 || echo "session-$(date +%s)-secret")")

  cat > "$ENV_FILE" <<EOF
# Qwen Gateway — Environment Variables
# Generated by install.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# DO NOT commit this file to version control!

# ── Database ────────────────────────────────────────────────────────────────
MONGODB_URI=${MONGODB_URI}
MONGODB_DATABASE=${MONGODB_DATABASE}

# ── Redis ───────────────────────────────────────────────────────────────────
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}

# ── PostgreSQL ──────────────────────────────────────────────────────────────
POSTGRES_URL=${POSTGRES_URL}

# ── Auth ────────────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
SESSION_SECRET=${SESSION_SECRET}

# ── Server ──────────────────────────────────────────────────────────────────
NODE_ENV=production
PORT=8080
EOF

  ok ".env written to ${ENV_FILE}"
fi

# Add .env to .gitignore if not already there
if [ -f ".gitignore" ]; then
  if ! grep -q "^\.env$" .gitignore; then
    echo ".env" >> .gitignore
    ok ".env added to .gitignore"
  fi
else
  echo ".env" > .gitignore
  ok ".gitignore created with .env entry"
fi

# ── 4. Build ──────────────────────────────────────────────────────────────────
step "Running typecheck & build"

pnpm run typecheck 2>&1 | tail -5
ok "Typecheck passed"

echo ""
info "Building API server..."
(
  set -a
  # shellcheck source=/dev/null
  [ -f .env ] && source .env
  set +a
  PORT=8080 pnpm --filter @workspace/api-server run build
) 2>&1 | tail -3
ok "API server built"

echo ""
info "Building frontend..."
(
  set -a
  [ -f .env ] && source .env
  set +a
  BASE_URL=/ pnpm --filter @workspace/gateway run build
) 2>&1 | tail -3
ok "Frontend built"

# ── 5. Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║          Installation complete! 🎉           ║${RESET}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "${BOLD}Next steps:${RESET}"
echo ""
echo -e "  ${CYAN}Development (with hot reload):${RESET}"
echo -e "    ${BOLD}pnpm --filter @workspace/api-server run dev${RESET}"
echo -e "    ${BOLD}pnpm --filter @workspace/gateway run dev${RESET}"
echo ""
echo -e "  ${CYAN}Production:${RESET}"
echo -e "    ${BOLD}PORT=8080 node --enable-source-maps artifacts/api-server/dist/index.mjs${RESET}"
echo ""
echo -e "  ${CYAN}API endpoints:${RESET}"
echo -e "    POST  /api/auth/register          — create account"
echo -e "    POST  /api/auth/login             — sign in → JWT"
echo -e "    POST  /api/apikeys                — generate API key (sk-dzcx...)"
echo -e "    POST  /v1/chat/completions        — OpenAI-compatible chat"
echo -e "    GET   /v1/models                  — list available models"
echo ""
echo -e "  ${CYAN}Available models (no token required):${RESET}"
echo -e "    • qwen3-235b-a22b  (fastest)"
echo -e "    • qwen3.7-max"
echo -e "    • qwen3-30b-a3b"
echo ""
echo -e "  ${CYAN}Compatible with OpenAI SDK:${RESET}"
cat <<'SNIPPET'
    import OpenAI from "openai";
    const client = new OpenAI({
      apiKey: "sk-dzcx...",
      baseURL: "http://localhost:8080/v1",
    });
SNIPPET
echo ""
