/**
 * Blackbox AI Provider
 *
 * Recon findings (g4f-style reverse engineering):
 *   Endpoint  : POST https://app.blackbox.ai/api/chat
 *   Auth      : static "validated" UUID from JS bundle (module 5217, fI export)
 *               bypasses anti-scraping; premium session cookie needed for full access
 *   Session   : set BLACKBOX_SESSION env var to your NextAuth session cookie value
 *               format: "next-auth.session-token=<jwt>"
 *   Response  : plain-text stream (app.blackbox.ai) or SSE (www.blackbox.ai)
 *
 * Supported models (mapped to Blackbox userSelectedModel values):
 *   blackboxai            → default Blackbox AI model
 *   blackbox-claude       → claude-sonnet-20241022
 *   blackbox-gpt4         → gpt-4o
 *   blackbox-deepseek-r1  → deepseek-ai/DeepSeek-R1
 *   blackbox-llama        → Meta-Llama-3.1-70B-Instruct-Turbo
 *   blackbox-qwen         → Qwen/Qwen2.5-Coder-32B-Instruct
 */

import { randomUUID } from "crypto";
import { logger } from "./logger";

const CHAT_EP  = "https://app.blackbox.ai/api/chat";
const ORIGIN   = "https://app.blackbox.ai";
const VALIDATED = "c3e9fc85-39df-41a0-8799-ba936d58ebe6";

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36";

// Map our model IDs → Blackbox's userSelectedModel values
const MODEL_MAP: Record<string, string> = {
  "blackboxai":           "blackboxai",
  "blackbox-claude":      "claude-sonnet-20241022",
  "blackbox-gpt4":        "gpt-4o",
  "blackbox-deepseek-r1": "deepseek-ai/DeepSeek-R1",
  "blackbox-llama":       "Meta-Llama-3.1-70B-Instruct-Turbo",
  "blackbox-qwen":        "Qwen/Qwen2.5-Coder-32B-Instruct",
};

export const BLACKBOX_MODELS = Object.keys(MODEL_MAP).map(id => ({
  id,
  object: "model" as const,
  created: 1748736000,
  owned_by: "blackbox",
}));

export function isBlackboxModel(model: string): boolean {
  return model in MODEL_MAP;
}

export interface ChatMessage {
  role: string;
  content: string;
}

// ── Request builder ───────────────────────────────────────────────────────────

function buildMessages(messages: ChatMessage[]): Array<{ role: string; content: string; id: string }> {
  return messages.map(m => ({
    role: m.role,
    content: m.content,
    id: randomUUID(),
  }));
}

function buildBody(messages: ChatMessage[], model: string): string {
  const bbModel = MODEL_MAP[model] ?? "blackboxai";
  return JSON.stringify({
    messages: buildMessages(messages),
    id: randomUUID(),
    previewToken: null,
    userId: null,
    codeModelMode: true,
    agentMode: {},
    trendingAgentMode: {},
    isMicMode: false,
    userSystemPrompt: null,
    maxTokens: 2048,
    playgroundTopP: null,
    playgroundTemperature: null,
    isChromeExt: false,
    githubToken: null,
    clickedAnswer2: false,
    clickedAnswer3: false,
    clickedForceWebSearch: false,
    visitFromDelta: false,
    mobileClient: false,
    userSelectedModel: bbModel,
    validated: VALIDATED,
  });
}

function buildHeaders(): Record<string, string> {
  const sessionCookie = process.env.BLACKBOX_SESSION ?? "";
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "User-Agent": UA,
    "Origin": ORIGIN,
    "Referer": `${ORIGIN}/chat`,
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.9",
  };
  if (sessionCookie) {
    headers["Cookie"] = sessionCookie;
  }
  return headers;
}

// ── Response parser ───────────────────────────────────────────────────────────

const PROMO_MARKERS = [
  "Generated by BLACKBOX.AI",
  "You have not upgraded your account",
  "Please upgrade to a premium plan",
  "Authentication Error",
  "rate limit",
];

function isPromoOrError(text: string): boolean {
  return PROMO_MARKERS.some(m => text.includes(m));
}

/** Parse Blackbox SSE stream line into text token (returns null for non-text events). */
function parseSSELine(line: string): string | null {
  if (!line.startsWith("data: ")) return null;
  const raw = line.slice(6).trim();
  if (raw === "[DONE]") return null;
  // Try JSON event format: {"type":"textResponse","text":"..."}
  try {
    const j = JSON.parse(raw) as Record<string, unknown>;
    if (j.type === "error") {
      const errText = String(j.errorText ?? "");
      throw new Error(`Blackbox error: ${errText}`);
    }
    if (j.type === "start" || j.type === "end") return null;
    if (typeof j.text === "string") return j.text;
    if (typeof j.content === "string") return j.content;
    // Generic: return any string-valued field named "message" or "response"
    for (const key of ["message", "response", "delta"]) {
      if (typeof j[key] === "string") return j[key] as string;
    }
    return null;
  } catch (e) {
    // Not JSON — might be raw text chunk
    if (!raw.startsWith("{")) return raw;
    throw e;
  }
}

/** Collect full response from a plain-text or SSE body string. */
function parseBody(raw: string): { content: string; inputTokens: number; outputTokens: number } {
  const lines = raw.split("\n");
  let content = "";
  let isSSE = false;

  for (const line of lines) {
    if (line.startsWith("data: ")) {
      isSSE = true;
      try {
        const token = parseSSELine(line);
        if (token) content += token;
      } catch { /* skip error lines */ }
    }
  }

  // If no SSE lines, treat whole body as plain text
  if (!isSSE) content = raw.trim();

  // Strip markdown links added by Blackbox (e.g. [upgrade](https://...))
  content = content.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").trim();

  const inputEst = 0;
  const outputEst = Math.round(content.length / 4);
  return { content, inputTokens: inputEst, outputTokens: outputEst };
}

// ── Streaming ─────────────────────────────────────────────────────────────────

export async function* blackboxStream(
  messages: ChatMessage[],
  model = "blackboxai",
): AsyncGenerator<string> {
  const body = buildBody(messages, model);
  const headers = buildHeaders();

  logger.debug({ model, bbModel: MODEL_MAP[model] }, "blackbox: sending request");

  const res = await fetch(CHAT_EP, {
    method: "POST",
    headers,
    body,
    signal: AbortSignal.timeout(60_000),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Blackbox HTTP ${res.status}: ${errText.slice(0, 200)}`);
  }

  if (!res.body) throw new Error("Blackbox: no response body");

  const reader = (res.body as unknown as { getReader(): ReadableStreamDefaultReader<Uint8Array> }).getReader();
  const dec = new TextDecoder();
  let buf = "";
  let accumulated = "";
  let isSSE = false;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    if (!value) continue;

    buf += dec.decode(value, { stream: true });
    const lines = buf.split("\n");
    buf = lines.pop() ?? "";

    for (const line of lines) {
      if (line.startsWith("data: ")) {
        isSSE = true;
        try {
          const token = parseSSELine(line);
          if (token) {
            accumulated += token;
            if (!isPromoOrError(accumulated)) yield token;
          }
        } catch (e) {
          logger.warn({ err: String(e) }, "blackbox: SSE parse error");
        }
      } else if (!isSSE && line.trim()) {
        accumulated += line + "\n";
      }
    }
  }

  // Flush remaining buffer
  if (buf.trim()) {
    if (buf.startsWith("data: ")) {
      try {
        const token = parseSSELine(buf);
        if (token && !isPromoOrError(accumulated + token)) yield token;
      } catch { /* ignore */ }
    } else if (!isSSE) {
      accumulated += buf;
    }
  }

  // If we collected plain text (non-SSE), yield it all at once
  if (!isSSE && accumulated.trim()) {
    const cleaned = accumulated.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").trim();
    if (!isPromoOrError(cleaned)) {
      yield cleaned;
    } else {
      throw new Error(`Blackbox: ${cleaned.slice(0, 150)}`);
    }
  }

  // Check if accumulated SSE content was promo/error
  if (isSSE && accumulated && isPromoOrError(accumulated)) {
    const cleaned = accumulated.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").trim();
    throw new Error(`Blackbox: ${cleaned.slice(0, 150)}`);
  }
}

// ── Non-streaming ─────────────────────────────────────────────────────────────

export async function blackboxChat(
  messages: ChatMessage[],
  model = "blackboxai",
): Promise<{ content: string; inputTokens: number; outputTokens: number }> {
  const body = buildBody(messages, model);
  const headers = buildHeaders();

  logger.debug({ model, bbModel: MODEL_MAP[model] }, "blackbox: non-stream request");

  const res = await fetch(CHAT_EP, {
    method: "POST",
    headers,
    body,
    signal: AbortSignal.timeout(60_000),
  });

  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Blackbox HTTP ${res.status}: ${errText.slice(0, 200)}`);
  }

  const raw = await res.text();

  if (isPromoOrError(raw)) {
    const cleaned = raw.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").trim();
    throw new Error(`Blackbox: ${cleaned.slice(0, 150)}`);
  }

  const result = parseBody(raw);
  if (!result.content) {
    throw new Error("Blackbox: empty response");
  }
  return result;
}
